# Generated by Django 5.1.1 on 2024-10-01 22:39

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XE_Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=50, verbose_name='Categoría Juego')),
            ],
        ),
        migrations.CreateModel(
            name='XE_Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Región')),
            ],
        ),
        migrations.CreateModel(
            name='XE_TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=50, verbose_name='Tipo usuario')),
            ],
        ),
        migrations.CreateModel(
            name='XE_Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=50, verbose_name='Tipo usuario')),
                ('precio', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.xe_categoria')),
            ],
        ),
        migrations.CreateModel(
            name='XE_Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=150, verbose_name='Nombre')),
                ('username', models.TextField(max_length=150, verbose_name='Nombre de usuario')),
                ('password', models.TextField(max_length=150, verbose_name='Contraseña')),
                ('email', models.EmailField(max_length=250, unique=True, verbose_name='Correo')),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='CL', verbose_name='Teléfono')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.xe_region', verbose_name='Región')),
                ('tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.xe_tipousuario', verbose_name='Tipo')),
            ],
        ),
    ]
