# Generated by Django 5.1.1 on 2024-10-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xe_categoria',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Categoría Juego'),
        ),
        migrations.AlterField(
            model_name='xe_juego',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Tipo usuario'),
        ),
        migrations.AlterField(
            model_name='xe_tipousuario',
            name='descripcion',
            field=models.CharField(max_length=50, verbose_name='Tipo usuario'),
        ),
        migrations.AlterField(
            model_name='xe_usuario',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='xe_usuario',
            name='password',
            field=models.CharField(max_length=150, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='xe_usuario',
            name='username',
            field=models.CharField(max_length=150, verbose_name='Nombre de usuario'),
        ),
    ]
